# 全局配置：重新部署所需文件
files_to_redeploy:
  dir: files-to-redeploy
  download_url: https://ghproxy.19882008.xyz/https://github.com/cmliu/edgetunnel/archive/refs/heads/main.zip

# Cloudflare Pages 部署账号
accounts:
  - name: cffc4@lancelot.dpdns.org
    enabled: false
    token: cfat_xxxxxxxxxxxxx_REPLACED_1
    account_id: c90461af64810c25832240efa660630b
    pages:
      project_name: share-main2c1m2
      domain: gy-cffc4-main-v1.lancelot.dpdns.org
      kv_namespace_id: ""
      kv_binding: KV
      project_type: production
    env:
      UUID:
        type: plain_text
        value: 31f549bd-6265-4099-a9c2-5ef86aada3a2
      ADMIN:
        type: plain_text
        value: li19882008

  - name: cffc1@lancelot.dpdns.org
    enabled: true
    token: cfat_xxxxxxxxxxxxx_REPLACED_2
    account_id: 0084357836d7d6771e9e13a4a055b980
    pages:
      project_name: gy-cffc1-node-v0
      domain: gy-cffc1-node-v0.lancelot.dpdns.org
      kv_namespace_id: gy-cffc1-node-v0
      kv_binding: KV
      project_type: production
    env:
      UUID:
        type: plain_text
        value: 31f549bd-6265-4099-a9c2-5ef86aada3a2
      ADMIN:
        type: plain_text
        value: li19882008

  - name: cffc2@lancelot.dpdns.org
    enabled: true
    token: cfat_xxxxxxxxxxxxx_REPLACED_3
    account_id: 52e6c70c617ec24018f81b0390dee4e9
    pages:
      project_name: gy-cffc2-node-v0
      domain: gy-cffc2-node-v0.lancelot.dpdns.org
      kv_namespace_id: gy-cffc2-node-v0
      kv_binding: KV
      project_type: production
    env:
      UUID:
        type: plain_text
        value: 31f549bd-6265-4099-a9c2-5ef86aada3a2
      ADMIN:
        type: plain_text
        value: li19882008

  - name: cffc3@lancelot.dpdns.org
    enabled: true
    token: cfat_xxxxxxxxxxxxx_REPLACED_4
    account_id: 01458142e4901fe5b803b8c517d572c2
    pages:
      project_name: gy-cffc3-node-v0
      domain: gy-cffc3-node-v0.lancelot.dpdns.org
      kv_namespace_id: gy-cffc3-node-v0
      kv_binding: KV
      project_type: production
    env:
      UUID:
        type: plain_text
        value: 31f549bd-6265-4099-a9c2-5ef86aada3a2
      ADMIN:
        type: plain_text
        value: li19882008

  - name: cffc5@lancelot.dpdns.org
    enabled: false
    token: cfat_xxxxxxxxxxxxx_REPLACED_5
    account_id: 60f05fb2379604f93f6410d013199d5f
    pages:
      project_name: gy-cffc5-node-v0
      domain: gy-cffc5-node-v0.lancelot.dpdns.org
      kv_namespace_id: gy-cffc5-node-v0
      kv_binding: KV
      project_type: production
    env:
      UUID:
        type: plain_text
        value: 31f549bd-6265-4099-a9c2-5ef86aada3a2
      ADMIN:
        type: plain_text
        value: li19882008
